mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

database:
  driverClassName: org.postgresql.Driver
  url: ${DATABASE_URL}
  username: ${DATABASE_USERNAME}
  password: ${DATABASE_PASSWORD}

jwtSecretKey: ${JWT_SECRET_KEY}
cors: ${CORS:http://localhost:3000}