### 1. 로그인 및 토큰 발급
POST http://localhost:8080/api/tokens
Content-Type: application/json

{
  "email": "restful@fitory.com",
  "password": "password123"
}

> {%
    // 서버가 준 Base64 인코딩 토큰을 가져온다.
    let encodedToken = response.body.accessToken;

    // atob() 함수를 사용하여 디코딩한다.
    let decodedToken = atob(encodedToken);

    // 디코딩된 '진짜 JWT 토큰'을 변수에 저장한다.
    client.global.set("auth_token", decodedToken);

    // 잘 풀렸는지 콘솔창에 출력한다.
    client.log("진짜 JWT 토큰: " + decodedToken);
%}

### 2. 컨트롤러에서 로그인 유저정보 추출
GET http://localhost:8080/api/tests
Content-Type: application/json
Authorization: Bearer {{auth_token}}