### 1. 회원가입 (POST /api/users)
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "email": "restful@fitory.com",
  "password": "password123"
}

### 2. 로그인 및 토큰 발급 (POST /api/tokens)
POST http://localhost:8080/api/tokens
Content-Type: application/json

{
  "email": "restful@fitory.com",
  "password": "password123"
}

> {%
    client.global.set("auth_token", response.body.accessToken);
%}

### 어드민으로 바로 로그인 테스트
POST http://localhost:8080/api/tokens
Content-Type: application/json

{
  "email": "1@a",
  "password": "admin123"
}

> {%
    client.global.set("auth_token", response.body.accessToken);
%}

### 3. 내 정보 조회 (GET /api/users/me)
GET http://localhost:8080/api/users/me
Authorization: Bearer {{auth_token}}

### 4. 어드민 대시보드 조회 (GET /api/admin-dashboards)
GET http://localhost:8080/api/admin-dashboards
Authorization: Bearer {{auth_token}}